### PR TITLE
Kos/sh 28  reading data for widget

### PR DESCRIPTION
**Pull request by kosich**
Refactored structure, added stub files for future modules

### CODE REVIEW

**Comment by kosich** [comment]
@antonSavk , @fortywinkz , @SergiiShust 

Please, review

**Comment by kucherenko** [comment]
probably we should add badges for CI?

btw, where are commits from developers?

**Comment by kosich** [comment]
@kucherenko 
yep, lets add appropriate tasks on next meeting
сommits from developers will be based on this branch

**Comment by antonSavk** [comment]
@kosich +

**Pull request merged**
